-- AlterTable
ALTER TABLE `reviews` MODIFY `createdAt` TIMESTAMP(4) NOT NULL DEFAULT CURRENT_TIMESTAMP(4);

-- AlterTable
ALTER TABLE `user` MODIFY `createdAt` TIMESTAMP(4) NOT NULL DEFAULT CURRENT_TIMESTAMP(4);
