

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network
    environment:
      - VITE_API_BACKEND=/api/

  server:
    env_file:
      - server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # - DATABASE_URL = in env
      - PRISMA_CLI_QUERY_ENGINE_TYPE=binary
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - VITE_API_BACKEND=http://server:3000/api/
      - CORS_ORIGIN=http://client:80
      - TZ=Europe/Moscow
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventsUaviak
      TZ: Europe/Moscow
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge